# -----------------------------------------------------------------------------
# Fluent Bit DaemonSet
# -----------------------------------------------------------------------------
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: efklog
  labels:
    k8s-app: fluent-bit-logging
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
    spec:
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 10
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      # Add init container to wait for Elasticsearch to be ready
      initContainers:
      - name: wait-for-elasticsearch
        image: alpine/curl:latest
        command:
        - sh
        - -c
        - |
          echo "Waiting for Elasticsearch to be ready..."
          until curl -k -v --output /dev/null --silent --head https://elasticsearch-logging-es-http.efklog.svc:9200; do
            echo "Elasticsearch not ready yet, waiting..."
            sleep 5
          done
          echo "Elasticsearch is ready!"
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:4.2.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 50Mi
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # Automatically read password from ECK-generated secret
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-logging-es-elastic-user
              key: elastic
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentbit-config
          mountPath: /fluent-bit/etc/
        # Mount ECK-generated CA certificate automatically
        - name: elasticsearch-certs
          mountPath: /etc/elasticsearch/certs
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentbit-config
        configMap:
          name: fluent-bit-config
      # Use ECK-generated certificate secret automatically
      - name: elasticsearch-certs
        secret:
          secretName: elasticsearch-logging-es-http-certs-public
          items:
          - key: ca.crt
            path: ca.crt