# -----------------------------------------------------------------------------
# Fluent Bit ServiceAccount
# -----------------------------------------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: efklog

---
# -----------------------------------------------------------------------------
# ClusterRole for Fluent Bit
# -----------------------------------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-reader
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "watch"]
---
# -----------------------------------------------------------------------------
# ClusterRoleBinding
# -----------------------------------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-reader
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: efklog